
services:
  app:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: shop/app
    ports:
      - "${APP_PORT}:8090"
    volumes:
      - "..:/app"
    networks:
      - shop_network
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    env_file:
      - .env
    image: postgres:17.3
    container_name: postgres_con
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - shop_network
    restart: unless-stopped

  pgadmin:
    env_file:
      - .env
    image: dpage/pgadmin4
    container_name: pgadmin_con
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - shop_network
    depends_on:
      - postgres


  redis:
    image: redis:alpine
    container_name: redis_con
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - shop_network
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
  redis:

networks:
  shop_network:
    driver: bridge